app_server/blueprints/auth.py
#!/usr/bin/python3
""" Guidy Blueprint """

from flask import *
from datetime import datetime
from uuid import uuid4
import re
from flask_login import LoginManager, login_user, login_required, logout_user, current_user
from app_server.blueprints.forms import *
from models import storage as db
from models.course import Course
from models.lesson import Lesson
from models.AI.AI_service import Guidy

auth = Blueprint('auth', __name__)
Manager = LoginManager()


@Manager.user_loader
def load_user(user_id):
    """ Load user """
    return db.session.query(User).get(user_id)

@auth.route('/login', methods=['GET', 'POST'])
def login():
    """ Landing page route handler"""
    form = LoginForm()
    if current_user.is_authenticated:
        # get_flashed_messages()
        return redirect(url_for('auth.dashboard'))
        

    if request.method == 'POST' and form.validate_on_submit():
        identity = form.username.data
        password = form.password.data

        if '@' in identity and '.' in identity and identity[-1] != '.':
            user = db.session.query(User).filter_by(email=identity).first()
        else:
            user = db.session.query(User).filter_by(username=identity).first()

        if user is not None and user.check_password(password):
            login_user(user)
            user.authenticated = True
            db.session.add(user)
            db.save()
            return redirect(url_for('auth.dashboard'))
        else:
            flash(f'{field}: {error}' for field, error in form.errors.items())

    return render_template('login.html', form=form)

@auth.route('/signup', methods=['GET', 'POST'])
def signup():
    """ Register page route handler"""
    form = RegisterForm()
    if form.validate_on_submit() and request.method == 'POST':
        username = form.username.data
        first_name = form.first_name.data
        last_name = form.last_name.data
        email = form.email.data
        password = form.password.data
        user = User(username=username, email=email,
                    first_name=first_name, last_name=last_name,
                    password=password)
        db.session.add(user)
        db.save()
        flash(f'User {user.username} created successfully!')
        return redirect(url_for('auth.login', cache_id=uuid4()))
    else:
        for field, error in form.errors.items():
            for err in error:
                flash(f'{field}: {err}')
    return render_template('signup.html', form=form,
                           cache_id=uuid4())

@auth.route('/logout', methods=['GET'])
@login_required
def logout():
    """ Logout page route handler"""
    user = current_user
    user.authenticated = False
    session.add(user)
    db.save()
    logout_user()
    return redirect(url_for('auth.login'))

@auth.route('/account', methods=['GET', 'POST'])
@login_required
def account():
    """ Profile page route handler"""
    form = ProfileForm()
    user = current_user
    if request.method == 'POST':
        user.first_name = form.first_name.data
        user.last_name = form.last_name.data
        user.email = form.email.data
        db.new(user)
        db.save()
        flash(f'User {user.username} updated successfully!')
        return render_template('account.html', user=user, form=form)
    else:
        for field, error in form.errors.items():
            for err in error:
                flash(f'{field}: {err}')

    return render_template('account.html', user=user, form=form)



@auth.route('/dashboard', methods=['GET'])
@login_required
def dashboard():
    """ dashboard page route handler"""
    user = current_user
    date = datetime.now()
    courses = user.courses
    return render_template('dashboard.html', user=user, courses=courses, date=date)

@auth.route('/courses/<coursename>/<course_id>', methods=['GET'])
@login_required
def course(coursename, course_id):
    """ Course page route handler"""
    user = current_user
    courses = [course for course in user.courses if course.id == course_id]
    course = courses[0]
    lessons = course.lessons_titles.replace("'", "\"")
    lessons = json.loads(lessons)
    return render_template('courses.html', course=course, lessons=lessons)

@auth.route('/new_course', methods=['GET', 'POST'])
@login_required
def new_course():
    """ Course page route handler"""
    form = CourseForm()
    user = current_user
    username = user.username

    if request.method == 'POST':
        subject = form.title.data
        categorey = form.category.data
        resource_type = form.resource_type.data
        level = form.level.data
        number_of_lessons = form.length.data
        print("Hello from new course")
        course = Guidy.CreateCourse(subject, level, number_of_lessons)
        generated_course = Course(title=course['title'],
                                  category=course['category'],
                                  description=course['description'],
                                  level=course['level'],
                                  length=course['length'],
                                  resource_type=resource_type,
                                  lessons_titles=course['lessons'])
        db.session.add(generated_course)
        user.courses.append(generated_course)
        db.save()
        return redirect(url_for('auth.course', username=username,
                                coursename=generated_course.title,
                                course_id=generated_course.id))
    return render_template('new_course.html', form=form)

@auth.route('/course/<course_id>/lesson/<lesson_num_str>', methods=['GET'])
# @login_required
def lesson(course_id, lesson_num_str):
    """ Course page route handler"""
    course = db.session.query(Course).filter_by(id = course_id).first()
    lesson_num = int(re.search(r'\d+', lesson_num_str).group())
    for lesson in course.lessons:
        if lesson.index == lesson_num:
            return lesson.description

    lessons = course.lessons_titles.replace("'", "\"")
    lessons_titles = json.loads(lessons)
    lesson_title = lessons_titles[lesson_num_str]
    lesson = Guidy.ExplainLesson(CourseSubject=course.title,
                                LessonTitle=lesson_title,
                                ResourcesType=course.resource_type)
    new_lesson = Lesson(index=lesson_num, title=lesson_title,
                        description=lesson['description'],
                        course_id=course_id)
    db.session.add(new_lesson)
    course.lessons.append(new_lesson)
    db.save()
    return lesson['description']

app_server/blueprints/views.py
#!/usr/bin/env python3
""" Blueprint module """

from flask import Blueprint, render_template

views = Blueprint('views', __name__)

@views.route('/')
def index():
    """ Landing page route handler"""
    return render_template('index.html')

@views.route('/about')
def about():
    """ About page route handler"""
    return render_template('about.html')

@views.route('/contact')
def contact():
    """ Contact page route handler"""
    return render_template('contact.html')

@views.route('/terms')
def terms():
    """ Terms page route handler"""
    return render_template('terms.html')

@views.route('/privacy')
def privacy():
    """ Privacy page route handler"""
    return render_template('privacy.html')

@views.route('/chat')
def chat():
    """ chat page route handler"""
    return render_template('chat.html')

app_server/templates/chat.html
<!doctype html>
<html lang="en" data-bs-theme="auto">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Courses generated by AI">
	<meta name="author" content="Mostafa Jamal, Tariq Abu-Elhamd and Bootstrap contributors">
	<title>Guidy</title>
	<link rel="shortcut icon" href="../static/images/icon.png" />
	<link href="../static/styles/main-min.css" rel="stylesheet">
	<link href="../static/node_modules/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
	<script src="../static/node_modules/bootstrap/js/color-modes.js"></script>
</head>

<body>
	<!-- theme icons -->
	<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
		<symbol id="circle-half" viewBox="0 0 16 16">
			<path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z" />
		</symbol>
		<symbol id="moon-stars-fill" viewBox="0 0 16 16">
			<path
				d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z" />
			<path
				d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z" />
		</symbol>
		<symbol id="sun-fill" viewBox="0 0 16 16">
			<path
				d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z" />
		</symbol>
	</svg>



	<!-- navbar -->
	<nav class="navbar navbar-expand-md sticky-top bg-body-tertiary shadow p-0">
		<div class="container-xxl">
			<!-- navbar brand / title -->
			<a class="navbar-brand" href="{{ url_for('views.index') }}">
				<img class="object-fit-scale" height="50" src="../static/images/logo.png" alt="Guidy" />
			</a>
			<!-- toggle button for mobile nav -->
			<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main-nav"
				aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
				<span class="navbar-toggler-icon"></span>
			</button>

			<!-- navbar links -->
			<div class="collapse navbar-collapse align-center justify-content-between" id="main-nav">
				<ul class="navbar-nav ">
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('auth.dashboard') }}">
							Dashboard
						</a>
					</li>
					<li class="nav-item">
						<a class="nav-link" href="{{ url_for('views.chat') }}">
							Chat
						</a>
					</li>
					<li class="nav-item d-none d-md-inline">
						<a class="btn btn-outline-primary" href="{{ url_for('auth.new_course') }}">
							Create
						</a>
					</li>
					<li class="nav-item d-md-none">
						<a class="nav-link" href="{{ url_for('auth.account') }}">
							account settings
						</a>
					</li>
					<li class="nav-item d-md-none">
						<a class="nav-link" href="{{ url_for('auth.logout') }}">
							Logout
						</a>
					</li>
					<li class="nav-item d-md-none">
						<a class="nav-link" href="{{ url_for('auth.new_course') }}">
							New course...
						</a>
					</li>
				</ul>
				<!-- theme change element -->
				<div class="d-flex align-items-center ms-auto">
					<div class="nav-item dropdown bd-mode-toggle">
						<button class="btn btn-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme"
							type="button" aria-expanded="false" data-bs-toggle="dropdown"
							aria-label="Toggle theme (auto)">
							<svg class="bi my-1 theme-icon-active" width="1em" height="1em">
								<use href="#circle-half"></use>
							</svg>
							<!-- very important to theme change work -->
							<span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
						</button>
						<!-- theme list -->
						<ul class="dropdown-menu dropdown-menu shadow" aria-labelledby="bd-theme-text">
							<li>
								<button type="button" class="dropdown-item d-flex align-items-center"
									data-bs-theme-value="light" aria-pressed="false">
									<svg class="bi me-2 opacity-50" width="1em" height="1em">
										<use href="#sun-fill"></use>
									</svg>
									Light

								</button>
							</li>
							<li>
								<button type="button" class="dropdown-item d-flex align-items-center"
									data-bs-theme-value="dark" aria-pressed="false">
									<svg class="bi me-2 opacity-50" width="1em" height="1em">
										<use href="#moon-stars-fill"></use>
									</svg>
									Dark

								</button>
							</li>
							<li>
								<button type="button" class="dropdown-item d-flex align-items-center active"
									data-bs-theme-value="auto" aria-pressed="true">
									<svg class="bi me-2 opacity-50" width="1em" height="1em">
										<use href="#circle-half"></use>
									</svg>
									Auto

								</button>
							</li>
						</ul>
					</div>
				</div>

				<!-- Account dropdown button -->
				<div class="nav-item dropdown d-none d-md-inline">
					<button class="btn" type="button" aria-expanded="false" data-bs-toggle="dropdown">
						<i class="bi bi-person-circle h1 text-primary"></i>
					</button>
					<!-- account list -->
					<ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
						<li>
							<a class="dropdown-item" href="{{ url_for('auth.account') }}">
								Settings
							</a>
						</li>
						<li>
							<a class="dropdown-item" href="{{ url_for('auth.logout') }}">
								Logout
							</a>
						</li>
					</ul>
				</div>
			</div>
		</div>
	</nav>


	<!-- the rest of the body -->
	<div class="container-fluid row min-vh-100 w-100 m-0 p-0">

		<!-- the main content -->
		<main class="col-8 tab-content">
			<div class="tab-pane fade show active" id="lesson1" role="tabpanel" aria-labelledby="lessons-list">
				<h1 class="h1 m-3">Chat
				</h1>
				<p class="card-text placeholder-glow m-4">
					<span class="placeholder col-7"></span>
					<span class="placeholder col-4"></span>
					<span class="placeholder col-4"></span>
					<span class="placeholder col-6"></span>
					<span class="placeholder col-8"></span>
				</p>

			</div>

		</main>

	</div>
	<!-- Footer-->
	<footer class="p-3 border">
		<div class="container">
			<div class="row">
				<div class="text-center">
					<ul class="list-inline mb-2">
						<li class="list-inline-item"><a href="{{ url_for('views.about') }}">About</a></li>
						<li class="list-inline-item">⋅</li>
						<li class="list-inline-item"><a href="#!">Contact</a></li>
						<li class="list-inline-item">⋅</li>
						<li class="list-inline-item"><a href="{{ url_for('views.terms') }}">Terms of Use</a></li>
						<li class="list-inline-item">⋅</li>
						<li class="list-inline-item"><a href="{{ url_for('views.privacy') }}">Privacy Policy</a></li>
					</ul>
					<p class="text-muted small mb-4 mb-lg-0">&copy; Guidy 2024. All Rights Reserved.</p>
				</div>
				<!-- <div class="text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div> -->
			</div>
		</div>
	</footer>

	<script src="../static/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>

app_server/templates/dashboard.html
<!doctype html>
<html lang="en" data-bs-theme="auto">

<head>
	<meta charset="utf-8">
	<meta name="viewport" content="width=device-width, initial-scale=1">
	<meta name="description" content="Courses generated by AI">
	<meta name="author" content="Mostafa Jamal, Tariq Abu-Elhamd and Bootstrap contributors">
	<title>Guidy</title>
	<link rel="shortcut icon" href="../static/images/icon.png" />
	<link href="../static/styles/main-min.css" rel="stylesheet">
	<link href="../static/node_modules/bootstrap-icons/font/bootstrap-icons.min.css" rel="stylesheet" />
	<script src="../static/node_modules/bootstrap/js/color-modes.js"></script>
</head>

<header class="sticky-top">
		<!-- theme icons -->
		<svg xmlns="http://www.w3.org/2000/svg" class="d-none">
			<symbol id="circle-half" viewBox="0 0 16 16">
				<path d="M8 15A7 7 0 1 0 8 1v14zm0 1A8 8 0 1 1 8 0a8 8 0 0 1 0 16z" />
			</symbol>
			<symbol id="moon-stars-fill" viewBox="0 0 16 16">
				<path
					d="M6 .278a.768.768 0 0 1 .08.858 7.208 7.208 0 0 0-.878 3.46c0 4.021 3.278 7.277 7.318 7.277.527 0 1.04-.055 1.533-.16a.787.787 0 0 1 .81.316.733.733 0 0 1-.031.893A8.349 8.349 0 0 1 8.344 16C3.734 16 0 12.286 0 7.71 0 4.266 2.114 1.312 5.124.06A.752.752 0 0 1 6 .278z" />
				<path
					d="M10.794 3.148a.217.217 0 0 1 .412 0l.387 1.162c.173.518.579.924 1.097 1.097l1.162.387a.217.217 0 0 1 0 .412l-1.162.387a1.734 1.734 0 0 0-1.097 1.097l-.387 1.162a.217.217 0 0 1-.412 0l-.387-1.162A1.734 1.734 0 0 0 9.31 6.593l-1.162-.387a.217.217 0 0 1 0-.412l1.162-.387a1.734 1.734 0 0 0 1.097-1.097l.387-1.162zM13.863.099a.145.145 0 0 1 .274 0l.258.774c.115.346.386.617.732.732l.774.258a.145.145 0 0 1 0 .274l-.774.258a1.156 1.156 0 0 0-.732.732l-.258.774a.145.145 0 0 1-.274 0l-.258-.774a1.156 1.156 0 0 0-.732-.732l-.774-.258a.145.145 0 0 1 0-.274l.774-.258c.346-.115.617-.386.732-.732L13.863.1z" />
			</symbol>
			<symbol id="sun-fill" viewBox="0 0 16 16">
				<path
					d="M8 12a4 4 0 1 0 0-8 4 4 0 0 0 0 8zM8 0a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 0zm0 13a.5.5 0 0 1 .5.5v2a.5.5 0 0 1-1 0v-2A.5.5 0 0 1 8 13zm8-5a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2a.5.5 0 0 1 .5.5zM3 8a.5.5 0 0 1-.5.5h-2a.5.5 0 0 1 0-1h2A.5.5 0 0 1 3 8zm10.657-5.657a.5.5 0 0 1 0 .707l-1.414 1.415a.5.5 0 1 1-.707-.708l1.414-1.414a.5.5 0 0 1 .707 0zm-9.193 9.193a.5.5 0 0 1 0 .707L3.05 13.657a.5.5 0 0 1-.707-.707l1.414-1.414a.5.5 0 0 1 .707 0zm9.193 2.121a.5.5 0 0 1-.707 0l-1.414-1.414a.5.5 0 0 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .707zM4.464 4.465a.5.5 0 0 1-.707 0L2.343 3.05a.5.5 0 1 1 .707-.707l1.414 1.414a.5.5 0 0 1 0 .708z" />
			</symbol>
		</svg>
	
	
	
		<!-- navbar -->
		<nav class="navbar navbar-expand-md sticky-top bg-body-tertiary shadow p-0">
			<div class="container-xxl">
				<!-- navbar brand / title -->
				<a class="navbar-brand" href="{{ url_for('views.index') }}">
					<img class="object-fit-scale" height="50" src="../static/images/logo.png" alt="Guidy" />
				</a>
				<!-- toggle button for mobile nav -->
				<button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#main-nav"
					aria-controls="main-nav" aria-expanded="false" aria-label="Toggle navigation">
					<span class="navbar-toggler-icon"></span>
				</button>
	
				<!-- navbar links -->
				<div class="collapse navbar-collapse align-center justify-content-between" id="main-nav">
					<ul class="navbar-nav ">
						<li class="nav-item">
							<a class="nav-link" href="#">
								Dashboard
							</a>
						</li>
						<li class="nav-item">
							<a class="nav-link" href="{{ url_for('views.chat') }}">
								Chat
							</a>
						</li>
						<li class="nav-item d-none d-md-inline">
							<a class="btn btn-outline-primary" href="{{ url_for('auth.new_course') }}">
								Create
							</a>
						</li>
						<li class="nav-item d-md-none">
							<a class="nav-link" href="{{ url_for('auth.account') }}">
								account settings
							</a>
						</li>
						<li class="nav-item d-md-none">
							<a class="nav-link" href="{{ url_for('auth.logout') }}">
								Logout
							</a>
						</li>
						<li class="nav-item d-md-none">
							<a class="nav-link" href="{{ url_for('auth.new_course') }}">
								New course...
							</a>
						</li>
					</ul>
					<!-- theme change element -->
					<div class="d-flex align-items-center ms-auto">
						<div class="nav-item dropdown bd-mode-toggle">
							<button class="btn btn-primary py-2 dropdown-toggle d-flex align-items-center" id="bd-theme"
								type="button" aria-expanded="false" data-bs-toggle="dropdown"
								aria-label="Toggle theme (auto)">
								<svg class="bi my-1 theme-icon-active" width="1em" height="1em">
									<use href="#circle-half"></use>
								</svg>
								<!-- very important to theme change work -->
								<span class="visually-hidden" id="bd-theme-text">Toggle theme</span>
							</button>
							<!-- theme list -->
							<ul class="dropdown-menu dropdown-menu shadow" aria-labelledby="bd-theme-text">
								<li>
									<button type="button" class="dropdown-item d-flex align-items-center"
										data-bs-theme-value="light" aria-pressed="false">
										<svg class="bi me-2 opacity-50" width="1em" height="1em">
											<use href="#sun-fill"></use>
										</svg>
										Light
	
									</button>
								</li>
								<li>
									<button type="button" class="dropdown-item d-flex align-items-center"
										data-bs-theme-value="dark" aria-pressed="false">
										<svg class="bi me-2 opacity-50" width="1em" height="1em">
											<use href="#moon-stars-fill"></use>
										</svg>
										Dark
	
									</button>
								</li>
								<li>
									<button type="button" class="dropdown-item d-flex align-items-center active"
										data-bs-theme-value="auto" aria-pressed="true">
										<svg class="bi me-2 opacity-50" width="1em" height="1em">
											<use href="#circle-half"></use>
										</svg>
										Auto
	
									</button>
								</li>
							</ul>
						</div>
					</div>
	
					<!-- Account dropdown button -->
					<div class="nav-item dropdown d-none d-md-inline">
						<button class="btn" type="button" aria-expanded="false" data-bs-toggle="dropdown">
							<i class="bi bi-person-circle h1 text-primary"></i>
						</button>
						<!-- account list -->
						<ul class="dropdown-menu dropdown-menu-end shadow" aria-labelledby="bd-theme-text">
							<li>
								<a class="dropdown-item" href="{{ url_for('auth.account') }}">
									Settings
								</a>
							</li>
							<li>
								<a class="dropdown-item" href="{{ url_for('auth.logout') }}">
									Logout
								</a>
							</li>
						</ul>
					</div>
				</div>
			</div>
		</nav>	
</header>

<body>
	<h1 class="h1 m-5">Dashboard</h1>
	<!-- the rest of the body -->
	<div class="container justify-content-center min-vh-100 w-70 m-5">
		<div class="row mt-2">
			<div class="card col-4 m-0 b-2">
				<div class="card-body justify-content-center">
					<h4 class="card-title bt-1 mt-3">Hello {{ current_user.first_name }}</h4>
					<h5 class="card-title bt-1 mb-3">Welcome Back!</h5>
					<p class="card-text">Today is {{ date.strftime('%A %d %B %Y') }}</p>
					<p class="card-text">Time is {{ date.strftime('%H:%M') }}</p>
				</div>
			</div>
		</div>
		<!-- the main content -->
			<h1 class="mt-3">My Courses</h1>

			<div class="row">
				{% for course in courses %}
				<div class="col-md-6 mt-5">
					<div class="card m-2 b-2">
						<div class="card-body justify-content-center">
							<h4 class="card-title bt-1 mt-3">{{ course.title }}</h4>
							<p class="card-title bt-1 mb-3">{{ course.description }}</p>
							<p class="card-text">Created on {{ course.created_at.strftime('%A %d %B %Y') }}</p>
							<p class="card-text">Last updated on {{ course.updated_at.strftime('%A %d %B %Y') }}</p>
							<p class="card-text">Number of lessons: {{ course.length }}</p>
							<a href="{{ url_for('auth.course', coursename=course.title, course_id=course.id) }}" class="btn btn-primary">View</a>
						</div>
					</div>
				</div>
				{% endfor %}
			</div>

	</div>
	<!-- Footer-->
	<footer class="p-3 border">
		<div class="container">
			<div class="row">
				<div class="text-center">
					<ul class="list-inline mb-2">
						<li class="list-inline-item"><a href="{{ url_for('views.about') }}">About</a></li>
						<li class="list-inline-item">⋅</li>
						<li class="list-inline-item"><a href="#!">Contact</a></li>
						<li class="list-inline-item">⋅</li>
						<li class="list-inline-item"><a href="{{ url_for('views.terms') }}">Terms of Use</a></li>
						<li class="list-inline-item">⋅</li>
						<li class="list-inline-item"><a href="{{ url_for('views.privacy') }}">Privacy Policy</a></li>
					</ul>
					<p class="text-muted small mb-4 mb-lg-0">&copy; Guidy 2024. All Rights Reserved.</p>
				</div>
				<!-- <div class="text-center text-lg-end my-auto">
                        <ul class="list-inline mb-0">
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-facebook fs-3"></i></a>
                            </li>
                            <li class="list-inline-item me-4">
                                <a href="#!"><i class="bi-twitter fs-3"></i></a>
                            </li>
                            <li class="list-inline-item">
                                <a href="#!"><i class="bi-instagram fs-3"></i></a>
                            </li>
                        </ul>
                    </div> -->
			</div>
		</div>
	</footer>

	<script src="../static/node_modules/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
</body>

</html>